"""empty message

Revision ID: 233e4c6333cd
Revises: d6528c3ab68e
Create Date: 2024-02-27 19:01:43.526274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e4c6333cd'
down_revision = 'd6528c3ab68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('sport')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('league_name')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
