"""empty message

Revision ID: 5dc756ea64eb
Revises: 410678c9c20a
Create Date: 2024-03-04 19:24:23.225157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc756ea64eb'
down_revision = '410678c9c20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('var_profit_percent', sa.Float(), nullable=True))

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('var_profit_percent', sa.Float(), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('var_profit_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('var_profit_percent')
        batch_op.drop_column('avg_profit_percent')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('var_profit_percent')
        batch_op.drop_column('avg_profit_percent')

    with op.batch_alter_table('bookies', schema=None) as batch_op:
        batch_op.drop_column('var_profit_percent')
        batch_op.drop_column('avg_profit_percent')

    # ### end Alembic commands ###
