"""empty message

Revision ID: 6add351a9cda
Revises: 
Create Date: 2024-03-08 16:18:32.098215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6add351a9cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avg_profit_percent', sa.Float(), nullable=True),
    sa.Column('var_profit_percent', sa.Float(), nullable=True),
    sa.Column('last_updated_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avg_profit_percent', sa.Float(), nullable=True),
    sa.Column('var_profit_percent', sa.Float(), nullable=True),
    sa.Column('last_updated_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('avg_profit_percent', sa.Float(), nullable=True),
    sa.Column('var_profit_percent', sa.Float(), nullable=True),
    sa.Column('last_updated_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('league_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id_leagues')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arbitrage_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneyline_1', sa.String(), nullable=True),
    sa.Column('moneyline_2', sa.String(), nullable=True),
    sa.Column('decimal_1', sa.Float(), nullable=True),
    sa.Column('decimal_2', sa.Float(), nullable=True),
    sa.Column('stake_1_percent', sa.Float(), nullable=True),
    sa.Column('stake_2_percent', sa.Float(), nullable=True),
    sa.Column('profit_percent', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('game_date', sa.String(), nullable=True),
    sa.Column('game_time', sa.String(), nullable=True),
    sa.Column('bookie_1_id', sa.Integer(), nullable=True),
    sa.Column('bookie_2_id', sa.Integer(), nullable=True),
    sa.Column('team_1_id', sa.Integer(), nullable=True),
    sa.Column('team_2_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookie_1_id'], ['bookies.id'], name=op.f('fk_arbitrage_opportunities_bookie_1_id_bookies')),
    sa.ForeignKeyConstraint(['bookie_2_id'], ['bookies.id'], name=op.f('fk_arbitrage_opportunities_bookie_2_id_bookies')),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_arbitrage_opportunities_league_id_leagues')),
    sa.ForeignKeyConstraint(['team_1_id'], ['teams.id'], name=op.f('fk_arbitrage_opportunities_team_1_id_teams')),
    sa.ForeignKeyConstraint(['team_2_id'], ['teams.id'], name=op.f('fk_arbitrage_opportunities_team_2_id_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arbitrage_opportunities')
    op.drop_table('teams')
    op.drop_table('users')
    op.drop_table('leagues')
    op.drop_table('bookies')
    # ### end Alembic commands ###
