"""empty message

Revision ID: c7f093b22bc3
Revises: 233e4c6333cd
Create Date: 2024-02-29 17:30:03.348268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f093b22bc3'
down_revision = '233e4c6333cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_arbitrage_opportunities')
    op.drop_table('team_arbitrage_opportunities')
    op.drop_table('bookie_arbitrage_opportunities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookie_arbitrage_opportunities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('arbitrage_opportunity_id', sa.INTEGER(), nullable=True),
    sa.Column('bookie_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['arbitrage_opportunity_id'], ['arbitrage_opportunities.id'], name='fk_bookie_arbitrage_opportunities_arbitrage_opportunity_id_arbitrage_opportunities'),
    sa.ForeignKeyConstraint(['bookie_id'], ['bookies.id'], name='fk_bookie_arbitrage_opportunities_bookie_id_bookies'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_arbitrage_opportunities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('arbitrage_opportunity_id', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['arbitrage_opportunity_id'], ['arbitrage_opportunities.id'], name='fk_team_arbitrage_opportunities_arbitrage_opportunity_id_arbitrage_opportunities'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_team_arbitrage_opportunities_team_id_teams'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_arbitrage_opportunities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('arbitrage_opportunity_id', sa.INTEGER(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['arbitrage_opportunity_id'], ['arbitrage_opportunities.id'], name='fk_league_arbitrage_opportunities_arbitrage_opportunity_id_arbitrage_opportunities'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name='fk_league_arbitrage_opportunities_league_id_leagues'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
