"""empty message

Revision ID: d6528c3ab68e
Revises: 4a4495412728
Create Date: 2024-02-27 18:54:59.691923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6528c3ab68e'
down_revision = '4a4495412728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookie_arbitrage_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arbitrage_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('bookie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arbitrage_opportunity_id'], ['arbitrage_opportunities.id'], name=op.f('fk_bookie_arbitrage_opportunities_arbitrage_opportunity_id_arbitrage_opportunities')),
    sa.ForeignKeyConstraint(['bookie_id'], ['bookies.id'], name=op.f('fk_bookie_arbitrage_opportunities_bookie_id_bookies')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arbitrage_opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moneyline_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('moneyline_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decimal_1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('decimal_2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stake_1_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stake_2_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('game_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('game_time', sa.String(), nullable=True))
        batch_op.alter_column('bookie_1_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('bookie_2_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('league_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('year')
        batch_op.drop_column('day')
        batch_op.drop_column('profit')
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arbitrage_opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('profit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('day', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=True))
        batch_op.alter_column('league_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('bookie_2_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('bookie_1_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('game_time')
        batch_op.drop_column('game_date')
        batch_op.drop_column('timezone')
        batch_op.drop_column('date')
        batch_op.drop_column('profit_percent')
        batch_op.drop_column('stake_2_percent')
        batch_op.drop_column('stake_1_percent')
        batch_op.drop_column('decimal_2')
        batch_op.drop_column('decimal_1')
        batch_op.drop_column('moneyline_2')
        batch_op.drop_column('moneyline_1')

    op.drop_table('bookie_arbitrage_opportunities')
    # ### end Alembic commands ###
